# Generated by Django 5.0.4 on 2024-05-14 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSchedules',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('days', models.IntegerField()),
                ('roomNo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('instructor', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('prerequisites', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='App.courses')),
                ('scheduled', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.courseschedules')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentReg',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.courses')),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.student')),
            ],
        ),
    ]
