# Generated by Django 5.0.4 on 2024-05-29 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='scheduled',
        ),
        migrations.AddField(
            model_name='courseschedules',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.courses'),
        ),
    ]
