# Generated by Django 5.0.4 on 2024-05-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_alter_studentreg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseschedules',
            name='days',
            field=models.CharField(choices=[('3-days', 'sunday-tuesday-thursday'), ('2-days', 'monday-wensday')], max_length=10, null=True),
        ),
    ]
