# Generated by Django 5.0.4 on 2024-05-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_alter_courseschedules_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='prerequisites',
        ),
        migrations.AddField(
            model_name='courses',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, to='App.courses'),
        ),
    ]
