# Generated by Django 5.0.6 on 2024-05-30 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_remove_courseschedules_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseschedules',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
