# Generated by Django 5.0.6 on 2024-05-30 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_alter_courseschedules_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseschedules',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
