# Generated by Django 5.0.6 on 2024-05-30 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_alter_courseschedules_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
